### PR TITLE
snpeff_db a string not a number

### PR DESCRIPTION
**Pull request by maxulysse**
Thanks to @YeHW

### CODE REVIEW

**Comment by maxulysse** [comment]
Lint failures will be fixed by #1140

**Review by FriederikeHanssen — COMMENTED** [review]
Hey! Did you test that this works when setting via the cli with just numbers? I remember there being issues with another parameter. Otherwise we might need to indicate somewhere that numbers need to be in quotes

**Comment by maxulysse** [comment]
> Hey! Did you test that this works when setting via the cli with just numbers? I remember there being issues with another parameter. Otherwise we might need to indicate somewhere that numbers need to be in quotes

Yeah, good point, I forgot about that, it fails on the command line, even with double quotes

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by maxulysse** [comment]
@nf-core-bot fix linting pretty please

**Pull request merged**
