### PR TITLE
feat: better logo on Github dark Mode

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jfy133 — APPROVED** [review]
omg that looks so sexi

**Comment by jfy133** [comment]
We need instructions how to make etc.

**Comment by ewels** [comment]
> We need instructions how to make etc.

Ideally, we need to code this so that it is made automatically. Logos are used by the `nf-core create` command and fetched dynamically from the website.

Code: https://github.com/nf-core/nf-co.re/blob/master/public_html/logo.php
URL: https://nf-co.re/logo?t=jamessmells

**Comment by maxulysse** [comment]
First step was just doing it manually for one, Sarek and Eager have always been outsiders on that matter, so it was a good idea to start with them.
I'll look at the code to make it for the other pipelines as well.

**Comment by jfy133** [comment]
> > We need instructions how to make etc.
> 
> Ideally, we need to code this so that it is made automatically. Logos are used by the `nf-core create` command and fetched dynamically from the website.
> 
> Code: https://github.com/nf-core/nf-co.re/blob/master/public_html/logo.php
> URL: https://nf-co.re/logo?t=jamessmells

I'm printing off the latter ;)

**Pull request merged**
