### PR TITLE
add CODEOWNERS file

### PR DESCRIPTION
**Pull request by MaxUlysse**
- add `CODEOWNERS` file to `TEMPLATE` branch

Many thanks to contributing to nf-core/sarek!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist
 - [X] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** [guidelines](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MaxUlysse** [comment]
I'm guessing template update should fix tests

**Comment by ewels** [comment]
Why does this need to go in to the `TEMPLATE` branch?

**Comment by MaxUlysse** [comment]
Because I think I should be responsible for code in this branch as well

**Comment by ewels** [comment]
Fair enough. I guess it shouldn’t mess with template syncing.. :thinking:

**Comment by ewels** [comment]
I wonder if this should go in to the tools template also? And use the author info?

**Comment by MaxUlysse** [comment]
I do agree, but I think we removed the GitHub handle from the template, to simplify the creation of a new pipeline.
Could be worth it to had it back

**Pull request merged**
