### PR TITLE
Fix GenomicsDB bug with mismatched intervals, remove duplicated variants from VQSR vcfs, add VQSR CI test

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
List of changes:

1. Adding at least stub test for VQSR (see #1027 ), attempts to get some actual teeny tiny data to run through failed
2. Removing duplicate entries in joint germline VQSR vcf by following instructions described [here](https://hpc.nih.gov/training/gatk_tutorial/vqsr.html) fixing #966 #1102. opting for this approach for now as it reduces the number of computational steps that need to be done.

3. Group on actual interval files and add relevant meta information to fix occasional grouping mismatches (#1137)
5. some channel renaming (#1042)
6. Refactor single sample filtering (#1053)

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by asp8200** [comment]
Should some of these improvements perhaps be "mirrored" or "copied" over into the sentieon-subworkflows?

**Comment by FriederikeHanssen** [comment]
> Should some of these improvements perhaps be "mirrored" or "copied" over into the sentieon-subworkflows?

sure, but in a separate PR imo. and not all is relevant due to the different structure

**Comment by FriederikeHanssen** [comment]
Tests are failing because of the generated csv file. We should decide which vcf files go in there and by extension get annotated: 

This is the current state for the joint_germline track. No gvcfs, but the output of genotypegvcf and then the one following recalibration.
```
patient,sample,variantcaller,vcf
all_samples,joint_variant_calling,haplotypecaller,results/variant_calling/haplotypecaller/joint_variant_calling/joint_germline.vcf.gz
all_samples,recalibrated_joint_variant_calling,haplotypecaller,results/variant_calling/haplotypecaller/recalibrated_joint_variant_calling/joint_germline_recalibrated.vcf.gz

```

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
code is looking good, still I think we need to fix some tests

**Comment by FriederikeHanssen** [comment]
fixing the samplesheet stuff at the moment. Should fix the tests, plus I added a sneaky docker tag in one one. Let me push things and get back to you on the tests

**Comment by FriederikeHanssen** [comment]
@nf-core-bot fix linting

**Pull request merged**
