### PR TITLE
Switching to bwa-mem2

### LINKED ISSUE #228: BWA Mem2 Stable release
Fresh release: 

Stable now: https://github.com/bwa-mem2/bwa-mem2/releases/tag/v2.0 :wink:

Claiming identical results with major speedups:

https://github.com/bwa-mem2/bwa-mem2#performance

### PR DESCRIPTION
**Pull request by MaxUlysse**
Close #228 

Tested it on my computer and it works, I can push the docker image, so CI will work as well.

@FriederikeHanssen @ggabernet I guess you are the ones to figure if you want it to be merged or not.
They do claim identical results with major speedups.

# nf-core/sarek pull request

Many thanks for contributing to nf-core/sarek!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by apeltzer** [comment]
Would be really interesting to see if its so much faster on GHA already ? ;-)

**Comment by MaxUlysse** [comment]
I'm sure it'll fail on GHA as the current `dev` on docker still has the old environment.

**Comment by MaxUlysse** [comment]
@apeltzer that's why I was commenting with that:
> Tested it on my computer and it works, I can push the docker image, so CI will work as well.

**Comment by MaxUlysse** [comment]
@szilvajuhos would be interesting to compare with sentieon

**Comment by MaxUlysse** [comment]
> Would be really interesting to see if its so much faster on GHA already ? ;-)

@apeltzer I think data is too small to show any improvments

**Comment by FriederikeHanssen** [comment]
Could test this with on of my tcga patients. That data sure is big

**Pull request merged**
