### PR TITLE
Fix duplicate substrings in tools and skip_tools

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by maxulysse** [comment]
do we really need to add this `split` on `tools`?

**Comment by FriederikeHanssen** [comment]
> do we really need to add this `split` on `tools`?

as far as I see it yes. 

`params.tools` is a string -> .split(',')  turns it into a list, new elements are detected by `,` -> then `markduplicates` and `markduplicates_report` are separate entries and can't both be detected by the same query

**Comment by maxulysse** [comment]
> > do we really need to add this `split` on `tools`?
> 
> as far as I see it yes.
> 
> `params.tools` is a string -> .split(',') turns it into a list, new elements are detected by `,` -> then `markduplicates` and `markduplicates_report` are separate entries and can't both be detected by the same query

Now I see, but we would need that only when we need to differentiate between `markduplicates` and `markduplicates_report`, not for any others?

**Comment by FriederikeHanssen** [comment]
> Now I see, but we would need that only when we need to differentiate between `markduplicates` and `markduplicates_report`, not for any others?

that is right, also for `baserecalibrator` . The rest I did more to have it the same way everywhere. But happy to reverse it.

**Comment by maxulysse** [comment]
No, it's fine, better be safe than sorry.

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
