### PR TITLE
Enable Spark for GATK

### LINKED ISSUE #64: Use spark for GATK
From @apeltzer cf https://github.com/SciLifeLab/Sarek/issues/730

> Might simply work like this: https://software.broadinstitute.org/gatk/documentation/article?id=11245
> 
> Copying the text from there over here:
> 
> > You don't need a Spark cluster to run Spark-enabled GATK tools!
> >
> > If you're working on a "normal" machine (even just a laptop) with multiple CPU cores, the GATK engine can still use Spark to create a virtual standalone cluster in place, and set it to take advantage of however many cores are available on the machine -- or however many you choose to allocate. See the example parameters below and the local-Spark tutorial for more information on how to control this. And if your machine only has a single core, these tools can always be run in single-core mode -- it'll just take longer for them to finish.
> >
> > To be clear, even the Spark-only tools can be run on regular machines, though in practice a few of them may be prohibitively slow (SV tools and PathSeq). See the Tool Docs for tool-specific recommendations.
> > 
> > If you do have access to a Spark cluster, the Spark-enabled tools are going to be extra happy but you may need to provide some additional parameters to use them effectively. See the cluster-Spark tutorial for more information.
> > Example command-line parameters
> > 
> > Here are some example arguments you would give to a Spark-enabled GATK tool:
```
    --spark-master local[*] -> "Run on the local machine using all cores"
    --spark-master local[2] -> "Run on the local machine using two cores" 
```
---
> Should be possible to run e.g. `picard markduplicates` like this, same for some other stuff such as `BaseRecalibrator` and `HaplotypeCaller`.
---
> https://gatkforums.broadinstitute.org/gatk/discussion/23441/markduplicatespark-is-slower-than-normal-markduplicates
>
> We should really look into this!
---
> Apparently it benefits when not sorting reads prior `MarkDuplicates` and takes direct `BWA mem` BAM output. So we should really try it :-)
---
> We should move this over to nf-core/sarek ;)
---
Moved over ;-)

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Add `GATK Spark` possibilities to Sarek
- Now use `gatk4-spark` instead of `gatk4`
- Remove `runOptions = "-u \$(id -u):\$(id -g)"` in `nextflow.config` to enable `Spark` possibilities
- Close #64

## PR checklist
 - [X] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
 - [X] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [X] Make sure your code lints (`nf-core lint .`).
 - [X] Documentation in `docs` is updated
 - [X] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** [guidelines](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MaxUlysse** [comment]
cf https://github.com/nf-core/tools/issues/336

**Comment by apeltzer** [comment]
Maybe we could add a comment to the template that pipelines using SPARK shouldn't have these options set?

**Comment by MaxUlysse** [comment]
No idea about that one is this `runOptions = "-u \$(id -u):\$(id -g)"` really that important?

**Comment by apeltzer** [comment]
We had some discussions whether we need it at all or should have it by default. Even in the nextflow issue tracker it's not been clear whether this should be a default setting in general for nextflows docker integration ...?

**Comment by MaxUlysse** [comment]
:warning:  Do not merge until `HaplotypeCaller` test is fixed.

**Pull request merged**
