### PR TITLE
Add create_pon.nf script

### PR DESCRIPTION
**Pull request by cgpu**
## ⚠️ **Still under construction** ⚠️ 
Pending tasks here: https://github.com/nf-core/sarek/issues/149
***

This PR adds a separate script to enable the generation of a somatic panel of normals resource for Mutect2.  The script implements the **Mutect2 Panel of Normals Workflow** described in the GATK tutorial ['How-to-Call-somatic-mutations-using-GATK4-Mutect2'](https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2), in the section shown below:

image

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MaxUlysse** [comment]
I'm adding @szilvajuhos as a reviewer as he did most of the work for integrating PONs within Sarek

**Comment by cgpu** [comment]
> I'm adding @szilvajuhos as a reviewer as he did most of the work for integrating PONs within Sarek

Thanks @MaxUlysse. Can you also add a `wip` label so I can remove it from the PR title? There are several tasks to be implemented still.

**Comment by cgpu** [comment]
> Cool, thank you, could you please add some documentation eventually?
> Cheers
> Szilva

Thanks Szilva, will do, still needs a few tasks that need to be implemented, I will create the issue for the feature addition and comment there the pending tasks. Feel free to add anything I might have neglected.

**Comment by maxulysse** [comment]
Added as a subworkflow https://github.com/nf-core/modules/pull/1044

**Pull request closed without merging**
