### PR TITLE
ASCAT exome/targeted sequencing resource file generation

### PR DESCRIPTION
**Pull request by ameynert**
Added instructions to generate resource files for running ASCAT on exome or targeted sequencing data. Tested resulting files on TWIST exome capture kit targets and a set of 74 tumour-normal pairs.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
❤️ Loooooooove it! Thank you so much! I am not going to reproduce this, but it looks great!

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by FriederikeHanssen** [comment]
Can you update the changelog?

**Comment by ameynert** [comment]
> Can you update the changelog?

Done!

**Review by lassefolkersen — CHANGES_REQUESTED** [review]
Nice work. Very useful 😄 
One comment about the now expanded `sarek/usage.md` section on ASCAT usage: It seems like it's skipping on any mention of whole-genome sequencing. As I recall, that _is_ possible out-of-the-box. Or not, I'm unsure. But regardless, it feels like if there is a long and detailed point about ASCAT exome data, then there should at least be a sentence saying what to do with ASCAT whole genome data, even if that sentence is just "it works out of the box":

**Comment by ameynert** [comment]
> Nice work. Very useful 😄 One comment about the now expanded `sarek/usage.md` section on ASCAT usage: It seems like it's skipping on any mention of whole-genome sequencing. As I recall, that _is_ possible out-of-the-box. Or not, I'm unsure. But regardless, it feels like if there is a long and detailed point about ASCAT exome data, then there should at least be a sentence saying what to do with ASCAT whole genome data, even if that sentence is just "it works out of the box":

Good shout. I've added a sentence at the start of that section to clarify.

**Comment by FriederikeHanssen** [comment]
😱 what is going on with all the failing tests

**Pull request merged**
