### PR TITLE
Revert md5sums for some csvs from the mutec2_manual test

### PR DESCRIPTION
**Pull request by asp8200**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by maxulysse — COMMENTED** [review]
Can you update changelog too?

**Comment by FriederikeHanssen** [comment]
Don't merge yet. I found some more issues with Mutect2 and this may be related

**Comment by FriederikeHanssen** [comment]
Can you check the what the file contains? I have rerun everything and it sticks with the original changed md5sum (f8...) and lloks like this: 

```
patient,sample,variantcaller,vcf
test3,sample4_vs_sample3,mutect2,results/variant_calling/mutect2/sample4_vs_sample3/sample4_vs_sample3.mutect2.filtered.vcf.gz
```
exactly as expected

**Comment by asp8200** [comment]
This will also be fixed by https://github.com/nf-core/sarek/pull/1220  so I'm closing this without merging.

**Pull request closed without merging**
