### PR TITLE
Testing aws test workflow

### PR DESCRIPTION
**Pull request by ggabernet**
Do not merge this PR, it is just for checking that the github actions AWS tests are run on PR to master.

@FriederikeHanssen @MaxUlysse

### CODE REVIEW

**Comment by MaxUlysse** [comment]
> Do not merge this PR, it is just for checking that the github actions AWS tests are run on PR to master.
> 
> @FriederikeHanssen @MaxUlysse

I don't think it will untill we merge `dev` to `master`

**Comment by FriederikeHanssen** [comment]
What about replacing master with dev just for checking it?

**Comment by ggabernet** [comment]
Right, just saw it was not triggered. Ok, I'll close it then.

**Comment by ggabernet** [comment]
> What about replacing master with dev just for checking it?

sure, why not, let's try

**Comment by MaxUlysse** [comment]
I'll let you both play with AWS then.
Have fun

**Pull request closed without merging**
