### PR TITLE
Subway update

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by lassefolkersen — APPROVED** [review]
Looks better!

**Comment by maxulysse** [comment]
Changelog?

**Review by jfy133 — APPROVED** [review]
Really nice! Much cleaner now IMO!

Only comment I would have is you could replace the slight red background to a light grey, but that's me being fussy ;)

**Comment by FriederikeHanssen** [comment]
> Really nice! Much cleaner now IMO!
> 
> Only comment I would have is you could replace the slight red background to a light grey, but that's me being fussy ;)

um what? where is a red background?

**Comment by maxulysse** [comment]
> > Really nice! Much cleaner now IMO!
> > Only comment I would have is you could replace the slight red background to a light grey, but that's me being fussy ;)
> 
> um what? where is a red background?

the gray background looks a little reddish, what is the gray you used?

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
