### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
Anything else that needs updating?

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by asp8200** [comment]
As we briefly talked about at the summit, I think "zoomed-version" of the variant-calling-figure is a bit misleading:

image

Just looking at the figure, I think one would be inclined to think that the variant-callers are being run sequentially and that the output from one variant-caller is being fed into the next. I think a figure, which should that the variant-callers are being run in parallel on (more or less) the same input, would be more appropriate. Just my two cents... Anyways, I don't see it as something important to fix for release 3.1. Perhaps we could just make a gitHub-issue on fixing that figure, and then get back to it later?

**Review by maxulysse — APPROVED** [review]

**Comment by asp8200** [comment]
Should the changelog be updated in this PR or will that be done later?

**Comment by FriederikeHanssen** [comment]
> As we briefly talked about at the summit, I think "zoomed-version" of the variant-calling-figure is a bit misleading:
> 
> image
> 
> Just looking at the figure, I think one would be inclined to think that the variant-callers are being run sequentially and that the output from one variant-caller is being fed into the next. I think a figure, which should that the variant-callers are being run in parallel on (more or less) the same input, would be more appropriate. Just my two cents... Anyways, I don't see it as something important to fix for release 3.1. Perhaps we could just make a gitHub-issue on fixing that figure, and then get back to it later?

sure you could open an issue with your sketch/suggestion on how to improve this. I don't have the capacaties to do that for this release. It would be nice if it would stay in the same format/dimension more or less as it nice for posters and such

**Comment by asp8200** [comment]
> > As we briefly talked about at the summit, I think "zoomed-version" of the variant-calling-figure is a bit misleading:
> > image
> > Just looking at the figure, I think one would be inclined to think that the variant-callers are being run sequentially and that the output from one variant-caller is being fed into the next. I think a figure, which should that the variant-callers are being run in parallel on (more or less) the same input, would be more appropriate. Just my two cents... Anyways, I don't see it as something important to fix for release 3.1. Perhaps we could just make a gitHub-issue on fixing that figure, and then get back to it later?
> 
> sure you could open an issue with your sketch/suggestion on how to improve this. I don't have the capacaties to do that for this release. It would be nice if it would stay in the same format/dimension more or less as it nice for posters and such

I'll just make a gitHub-issue for it, and then maybe somebody can take a look at that one day. As I mentioned, I don't think it is super important :-)

**Pull request merged**
