### PR TITLE
Remove fancy testing

### PR DESCRIPTION
**Pull request by Emiller88**

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]
❤️

**Comment by maxulysse** [comment]
Why removing all that new fancy CI?

**Comment by maxulysse** [comment]
Oh, I see that was what you were saying yesterday.
Then shall we merge this one?

**Comment by FriederikeHanssen** [comment]
I really really really want to :D let's do it, sorry Edmund 😆

**Comment by maxulysse** [comment]
We'll add it back later

**Pull request merged**
