### PR TITLE
Updates sarek_subway

### PR DESCRIPTION
**Pull request by nevinwu**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

This PR updates the metro map for sarek (sarek_subway) with lofreq. Closes https://github.com/nf-core/sarek/issues/1651

### CODE REVIEW

**Comment by nevinwu** [comment]
I have noticed now what you mean by this white padding now that I see the "Files changed" here in GitHub. Sorry.

I have tried to, but I can't find that option I don't really know how to do it. Could you guys please do it? :)

On the other side, I have updated the `CHANGELOG`.

**Comment by FriederikeHanssen** [comment]
@maxulysse actions are failing because of outdated actions. Should we merge anyways since no code changes were done?

**Comment by nevinwu** [comment]
What do you mean by "outdated actions"? I'm curious. 

> @maxulysse actions are failing because of outdated actions.

**Comment by FriederikeHanssen** [comment]
If you click on the 'Details' you can see the error messages of the failing ones and it says 

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

**Comment by maxulysse** [comment]
Can you save the whole page and not the drawing only when you export?

**Comment by nevinwu** [comment]
I think that it is correct now.

**Comment by maxulysse** [comment]
> @maxulysse actions are failing because of outdated actions. Should we merge anyways since no code changes were done?

WHAAT?

**Review by FriederikeHanssen — APPROVED** [review]

**Pull request merged**
