### PR TITLE
add def to all new_meta assignments

### PR DESCRIPTION
**Pull request by jemunro**
Solves #887

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
🤯 cool, I think there is another issue with a similar report, that we couldn't reproduce. Wondering though why this was only ever reported for mutect and never one of the other processes that have a similar setup

**Comment by jemunro** [comment]
I have done a bit more testing, the issue seems to arise when multiple channels are being mapped with `new_meta` being assigned concurrently.

`test.nf`:
```nextflow
num_samples = 10
num_intervals = 10

test_input = (1..num_samples)
    .collect { sample -> 
        [id: "sample_$sample" ] 
    }.collectMany { meta ->
        (1..num_intervals).collect { intvl ->  
            [meta, "${meta.id}.${intvl}.vcf.gz"]
        }
    }

workflow TEST1 {
    test_ch = Channel.fromList(test_input)
    test_ch.take(1).view { "test_ch[0]: $it"}
    
    test_ch
        .map { meta, vcf ->
            assert vcf.contains(meta.id)
            new_meta = [id: meta.id]
            assert vcf.contains(new_meta.id)
        }
}

workflow TEST2 {
    test_ch = Channel.fromList(test_input)
    test_ch.take(1).view { "test_ch[0]: $it"}
    
    test_ch
        .map { meta, vcf ->
            assert vcf.contains(meta.id)
            new_meta = [id: meta.id]
            assert vcf.contains(new_meta.id)
        }
    
    test_ch
        .map { meta, vcf ->
            assert vcf.contains(meta.id)
            new_meta = [id: meta.id]
            assert vcf.contains(new_meta.id)
        }
}

workflow TEST3 {
    test_ch = Channel.fromList(test_input)
    test_ch.take(1).view { "test_ch[0]: $it"}
    
    test_ch
        .map { meta, vcf ->
            assert vcf.contains(meta.id)
            def new_meta = [id: meta.id]
            assert vcf.contains(new_meta.id)
        }
    
    test_ch
        .map { meta, vcf ->
            assert vcf.contains(meta.id)
            def new_meta = [id: meta.id]
            assert vcf.contains(new_meta.id)
        }
}

workflow.onComplete { println "success: ${workflow.success}" }
```
workflow TEST1 succeeds:
```
$nextflow run test.nf -entry TEST1
N E X T F L O W  ~  version 22.10.1
Launching `test.nf` [tender_curran] DSL2 - revision: 8ab568d7c1
test_ch[0]: [[id:sample_1], sample_1.1.vcf.gz]
success: true
```
workflow TEST2 fails:
```
$nextflow run test.nf -entry TEST2
N E X T F L O W  ~  version 22.10.1
Launching `test.nf` [happy_jones] DSL2 - revision: 7e455e7fc0
test_ch[0]: [[id:sample_1], sample_1.1.vcf.gz]
assert vcf.contains(new_meta.id)
       |   |        |        |
       |   false    |        sample_1
       |            ['id':sample_1]
       sample_2.1.vcf.gz

 -- Check script 'test.nf' at line: 34 or see '.nextflow.log' file for more details
success: false
```
workflow TEST3 succeeds:
```
$nextflow run test.nf -entry TEST3
N E X T F L O W  ~  version 22.10.1
Launching `test.nf` [silly_lalande] DSL2 - revision: 7e455e7fc0
test_ch[0]: [[id:sample_1], sample_1.1.vcf.gz]
success: true
```

**Comment by FriederikeHanssen** [comment]
Awesome :) Once the merge conflicts are resolved, the tests should be triggered and we can merge

**Review by FriederikeHanssen — COMMENTED** [review]
Almost there 🚀 Just needs a small update to the changelog, please :)

**Comment by jemunro** [comment]
> Almost there 🚀 Just needs a small update to the changelog, please :)

Done 👍

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by FriederikeHanssen** [comment]
@maxulysse I think there is quite some overlap with you subMap PR. Would love your input here, whether using submaps supersedes using def.

**Comment by maxulysse** [comment]
> @maxulysse I think there is quite some overlap with you subMap PR. Would love your input here, whether using submaps supersedes using def.

Indeed, I believe https://github.com/nf-core/sarek/pull/896 will replace this PR.

**Comment by maxulysse** [comment]
closed, as #896 as removed the need for such addition to the pipeline.

@jemunro can you confirm that you're not seeing this problem anymore on the `dev` branch?

**Pull request closed without merging**
