### PR TITLE
Disable GATK filters when joint calling

### PR DESCRIPTION
**Pull request by amizeranschi**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by asp8200** [comment]
With the change introduced by this PR, the pipeline will "silently" skip the haplotypecaller-filter on joint-germline runs, right?  I'm just wondering whether it would be better to stop the pipeline (with meaningful err msg) if the user tries to run joint-germline with filtering or at least inform the user that the filtering is being skipped 🤔 

Here are some somewhat related scenarios where the pipeline issues a warning:

[[log.warn "If Haplotypecaller is specified, without `--dbsnp` or `--known_indels no filtering will be done. For filtering, please provide at least one of `--dbsnp` or `--known_indels`. ....](https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/workflows/sarek.nf#L113-L124)](https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/workflows/sarek.nf#L113-L124)

**Comment by amizeranschi** [comment]
@asp8200 I've seen some of those messages during my tests. To be honest, I was a bit puzzled about why the pipeline was still issuing those warnings, even when I had all of the options `--dbsnp`, `--known_indels` and `--known_snps` specified in my run command.

> I'm just wondering whether it would be better to stop the pipeline (with meaningful err msg) if the user tries to run joint-germline with filtering or at least inform the user that the filtering is being skipped

My worry here is that, in this scenario, the user doesn't really have a choice about turning VCF filtering on in the first place. It's just on by default, with an option for disabling it via `--skip_tools haplotypecaller_filter`. So we'd essentially stop the pipeline or warn the users about some pipeline logic that they didn't initiate, which might be confusing.

**Comment by asp8200** [comment]
> > I'm just wondering whether it would be better to stop the pipeline (with meaningful err msg) if the user tries to run joint-germline with filtering or at least inform the user that the filtering is being skipped
> 
> My worry here is that, in this scenario, the user doesn't really have a choice about turning VCF filtering on in the first place. It's just on by default, with an option for disabling it via `--skip_tools haplotypecaller_filter`. So we'd essentially stop the pipeline or warn the users about some pipeline logic that they didn't initiate, which might be confusing.

Also valid points. I don't have a strong opinion on this; just wanted to share my two cents. Perhaps somebody else will chip in as well.

Anyways, thanks for the PR.

**Comment by FriederikeHanssen** [comment]
So this established back the old behavior. The pipeline was not suppoed to do filtering for joint germline, but single sample only, (where it sometimes can be skipped because it takes a long time): https://gatk.broadinstitute.org/hc/en-us/articles/360035535932-Germline-short-variant-discovery-SNPs-Indels- 

I think we might need to refactor this subworkflow a bit to make it more intuitive.  and put the whole FilterVarianttranches/CNNScore part into a singlesample haplotypecaller subworkflow, but I would do that in a separate PR

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
