### PR TITLE
Added Minimap2 alignment

### PR DESCRIPTION
**Pull request by EgorGuga**
## Overview 

In this pull-reqest, we added the ability to align reads using the minimap2 tool. The use of the tool is justified by the fact that this tool is popular and is used in commercial solutions, particularly in [MegaBOLT](https://en.mgi-tech.com/products/software_info/6/).

P.S.
As long as the sort_bam variable is hardcoded as true a call of the minimap2 tool will not cause any problems.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
💥 nice. I'll take a more in depth look later, but i noticed there are no changes to the igenomes config, so the user would regenerate the index file each time, right? Is the index available in igenomes?

**Comment by EgorGuga** [comment]
We didn't find index in igenomes

**Comment by FriederikeHanssen** [comment]
ok we should pregenerate it and put it there. No need for users to recompute it everytime

**Comment by maxulysse** [comment]
> Did this get closed because it was merged in a separate PR? This seems like a useful feature to merge in now that the big 3.4.1 refactor is published.

Indeed, @EgorGuga any reason for the closing?
do you need any help into syncing the branch?

**Comment by EgorGuga** [comment]
I messed up a bit with rebasing into 3.4.1.
I'm planning to make a separate pull-request for the new version ( the code is already written, but it needs to be tested).

**Pull request closed without merging**
