### PR TITLE
Fix issue 114

### LINKED ISSUE #114: Missing Variant depths in MulitQC Report - Bcftools
With Sarek v2.5.2 on WES data (`--genome 'GRCh38' --input sample_all.tsv --tools HaplotypeCaller,Strelka,Manta --targetBED exome_capture.bed`) the Bcftools 'Variant depths' plot  in the MulitQC report is empty. This would be nice to have in the future.

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
Closes #114 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]
Looking good

**Comment by FriederikeHanssen** [comment]
> Looking good

Still not quite working and some hard coded stuff in the module that shouldn't be there. So far haven't found anyone with a similar problem on biostars/github

**Comment by maxulysse** [comment]
> > Looking good
> 
> Still not quite working and some hard coded stuff in the module that shouldn't be there. So far haven't found anyone with a similar problem on biostars/github

Yes, but easy to put in the configs

**Comment by FriederikeHanssen** [comment]
closing in favor of #638

**Pull request closed without merging**
