### PR TITLE
FIX: nf-prov usage

### PR DESCRIPTION
**Pull request by maxulysse**

### CODE REVIEW

**Comment by asp8200** [comment]
What does exactly does this PR fix?  I can run Sarek with the latest version of nf-plov, but it does give this warning:

```
WARN: Config setting `prov.formats` is not defined, no provenance reports will be produced
```

**Comment by maxulysse** [comment]
It removes the warning and produce a file

**Comment by asp8200** [comment]
> It removes the warning and produce a file

Ok, what is `pipeline_info/manifest_${trace_timestamp}.bco.json`?  Should it perhaps be mentioned in `output.md` along with the other pipeline_info-files? 
```
### Pipeline information

<details markdown="1">
<summary>Output files</summary>

- `pipeline_info/`
  - Reports generated by Nextflow: `execution_report.html`, `execution_timeline.html`, `execution_trace.txt` and `pipeline_dag.dot`/`pipeline_dag.svg`.
  - Reports generated by the pipeline: `pipeline_report.html`, `pipeline_report.txt` and 
```

By the way, those file names are not entirely correct. It should be `execution_report_<timestamp>.html`, etc.

**Review by asp8200 — APPROVED** [review]
LGTM

**Review by FriederikeHanssen — APPROVED** [review]
thanks for fixing 🚀

**Pull request merged**
