### PR TITLE
Make bcftools/stats produce variant depths for multiqc

### LINKED ISSUE #114: Missing Variant depths in MulitQC Report - Bcftools
With Sarek v2.5.2 on WES data (`--genome 'GRCh38' --input sample_all.tsv --tools HaplotypeCaller,Strelka,Manta --targetBED exome_capture.bed`) the Bcftools 'Variant depths' plot  in the MulitQC report is empty. This would be nice to have in the future.

### PR DESCRIPTION
**Pull request by SusiJo**
## PR checklist

Closes #114 and makes #526 obsolete. 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint .`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by SusiJo** [comment]
Please note that I've also made an update PR to [bcftools/stats](https://github.com/nf-core/modules/pull/1893).
If the `target_bed` should be added to the current PR, this would imply further changes to sarek. 

Strangely, if a `target_bed` is provided with `bcftools/stats`, it is not sufficient anymore to just provide the `vcf.gz`files. Instead, one would need to add a channel for the index files (`vcf.gz.tbi`files to be passed alongside the `vcf.gz`files) to `bcftools_stats`. 

If they are not provided this would raise an error like this one:
```
Command error:
  [E::idx_find_and_load] Could not retrieve index file for 'test.strelka.variants.vcf.gz'
  Failed to read from test.strelka.variants.vcf.gz: could not load index
```

**Comment by maxulysse** [comment]
There's a new version of the BCFTOOLS/STATS module with a target bed

**Comment by FriederikeHanssen** [comment]
> 

What would be the advantage/disadvantage here of providing the target bed? Is it recommended for wes data?

**Comment by maxulysse** [comment]
No idea, just noticed this new possibility with the module update

**Pull request closed without merging**
