### PR TITLE
Fix GHA issues 

### PR DESCRIPTION
**Pull request by apeltzer**
Fix first bit of november 16 issues.

# nf-core/sarek pull request

Many thanks for contributing to nf-core/sarek!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [x] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

### CODE REVIEW

**Comment by apeltzer** [comment]
This should help for new PRs opened to at least have the CI run through fine :-)

**Review by MaxUlysse — APPROVED** [review]

**Comment by MaxUlysse** [comment]
Thanks @apeltzer

**Comment by MaxUlysse** [comment]
@FriederikeHanssen we'll need to push that to `dsl2` too

**Comment by apeltzer** [comment]
Guess this should've been covered by template sinc

**Pull request merged**
