### PR TITLE
ADAM mark duplicates example

### PR DESCRIPTION
**Pull request by heuermh**
Informational only; do not merge

### CODE REVIEW

**Comment by MaxUlysse** [comment]
@heuermh  I'm trying to implement it in DSL2:
https://github.com/MaxUlysse/nf-core_sarek/blob/dsl2_adam/modules/nf-core/software/adam_transformalignments.nf

But no idea if it's working or not as I'm not sure what I need to do to set it up properly.
Currently have this issue:
```
  Error occurred during initialization of VM
  Too small maximum heap
```

Any tips?

**Comment by heuermh** [comment]
Awesome!  I'm still learning DSL2, this is very helpful!

> Currently have this issue:
>
> ```
>   Error occurred during initialization of VM
>   Too small maximum heap
> ```

I am not too sure about how memory configuration works in sarek, my guess is that here `--driver-memory ${task.memory.toGiga()}` isn't returning a reasonable amount.

Perhaps adding a memory-related label to the process would help, e.g. [`memory_max`](https://github.com/MaxUlysse/nf-core_sarek/blob/dsl2_adam/conf/base.config#L48)?

More generally, it might be useful to have a Spark options configuration parameter.  There are a ton of configuration parameters the user might want to tweak, especially if running Spark under Yarn or Kubernetes.  There is an example of this at

https://github.com/heuermh/bdg-nextflow/blob/master/markdup.nf#L19
https://github.com/heuermh/bdg-nextflow/blob/master/nextflow.config#L6

**Comment by FriederikeHanssen** [comment]
Hi @MaxUlysse ! I am playing around with this right now. I got past the `maximum heap issue` by adding `g` after the memory specification, so like this:
`       --driver-memory ${task.memory.toGiga()}g \
`
I got new problems now, but maybe this somehow helps?!

**Comment by heuermh** [comment]
Hello, @FriederikeHanssen!

>  I got past the `maximum heap issue` by adding `g` after the memory specification

Ah yes, that helps!  Sorry I missed it.

> `UnknownHostException: qbic003: Temporary failure in name resolution`

I have not seen these before. There are some Spark configuration settings that may be relevant to your network (e.g. `SPARK_LOCAL_IP`, `spark.driver.host`, `spark.driver.bindAddress`)

https://spark.apache.org/docs/latest/configuration.html#networking

**Comment by FriederikeHanssen** [comment]
Hm, so I have the exact same error message when running `MarkDuplicatesSpark` with singularity. If I run `MarkDuplicatesSpark` with conda it works. So I will try the same now with `ADAM`. So maybe some parameter has to to be passed to the container

**Comment by heuermh** [comment]
Hello @FriederikeHanssen!  I noticed in the https://github.com/heroku/spark-singularity project, which provides configuration to run Spark under Singularity on Heroku, they specify

```
export SPARK_LOCAL_IP=127.0.0.1
export SPARK_PUBLIC_DNS=127.0.0.1
```

https://github.com/heroku/spark-singularity/blob/master/conf/singularity-overrides/spark-env.sh

Perhaps this might work for you?

**Comment by FriederikeHanssen** [comment]
This seems do do the trick (tested with docker image transformed to singularity):

```
// Import generic module functions
include { initOptions; saveFiles; getSoftwareName } from './functions'

params.options = [:]
def options    = initOptions(params.options)

process MD_ADAM{
    label 'process_high'
    publishDir "${params.outdir}",
        mode: params.publish_dir_mode,
        saveAs: { filename -> saveFiles(filename:filename, options:params.options, publish_dir:'mark_duplicates', publish_id:'') }
    
    conda (params.enable_conda ? "bioconda::adam=0.32.0--0" : null)
    if (workflow.containerEngine == 'singularity' && !params.pull_docker_container) {
        container "https://depot.galaxyproject.org/singularity/adam:0.32.0--0"
    } else {
        container "quay.io/biocontainers/adam:0.32.0--0"
    }

    input:
        tuple val(name), path(cram)
        path(reference)

    output:

    script:
    def software = getSoftwareName(task.process)
   
    """
    export SPARK_LOCAL_IP=127.0.0.1
    export SPARK_PUBLIC_DNS=127.0.0.1
    adam-submit \
       --master local[*] \
       -- \
       transformAlignments \
       -mark_duplicate_reads \
       -single \
       -reference ${reference} \
       -sort_by_reference_position \
       ${cram} \
       ${cram.simpleName}.md.cram
    """
}
```

I will now test again whether it still works with conda like that. But I think otherwise it can be set if the wf is run with singularity/docker, but not with conda. 

I now have a new problem. but this I think is related to me trying to use crams instead of bams. I am using the same reference that I had to create the cram. However, it throws this error:

```
Caused by: htsjdk.samtools.cram.CRAMException: Contig chr1 not found in the reference file.
```

`MarkDuplicatesSpark`works for the same cram file though. I couldn't find any issues related to this on ADAM Github Repo. But do you know anything? Whether this is a known issue or so?

**Comment by heuermh** [comment]
If you're sure the reference matches (i.e. `chr1` vs `1`), then perhaps the problem is that htsjdk (library used by adam) can't read the reference path at all.  What does the reference path look like?  Is it on local disk or cloud storage?

**Comment by FriederikeHanssen** [comment]
Hi @heuermh ,

I saw that ADAM had a new release and tried using it on BAM files. My process looks like this:

```
// Import generic module functions
include { initOptions; saveFiles; getSoftwareName } from './functions'

params.options = [:]
def options    = initOptions(params.options)

process MD_ADAM_BAM{
    label 'process_high'
    publishDir "${params.outdir}",
        mode: params.publish_dir_mode,
        saveAs: { filename -> saveFiles(filename:filename, options:params.options, publish_dir:'mark_duplicates', publish_id:'') }
    
    conda (params.enable_conda ? "bioconda::adam=0.33.0--0" : null)
    if (workflow.containerEngine == 'singularity' && !params.pull_docker_container) {
        container "https://depot.galaxyproject.org/singularity/adam:0.33.0--0"
    } else {
        container "quay.io/biocontainers/adam:0.33.0--0"
    }

    input:
        tuple val(name), path(bam)

    output:
        tuple val(name), path('*adam.md.bam')


    script:
    def software = getSoftwareName(task.process)
   
    """
    export SPARK_LOCAL_IP=127.0.0.1
    export SPARK_PUBLIC_DNS=127.0.0.1
    adam-submit \
       --master local[${task.cpus}] \
       --driver-memory ${task.memory.toGiga()}g \
       -- \
       transformAlignments \
       -mark_duplicate_reads \
       -single \
       -stringency LENIENT \
       ${bam}\
       ${bam.simpleName}.adam.md.bam
    """
}
```

I am getting this error:

```
 Suppressed: java.io.IOException: No space left on device
                at java.base/java.io.FileOutputStream.writeBytes(Native Method)
                at java.base/java.io.FileOutputStream.write(FileOutputStream.java:355)
                at org.apache.spark.storage.TimeTrackingOutputStream.write(TimeTrackingOutputStream.java:59)
                at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
                at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
                at net.jpountz.lz4.LZ4BlockOutputStream.flush(LZ4BlockOutputStream.java:243)
                at org.apache.spark.serializer.DummySerializerInstance$1.flush(DummySerializerInstance.java:50)
                at org.apache.spark.storage.DiskBlockObjectWriter.commitAndGet(DiskBlockObjectWriter.scala:173)
                at org.apache.spark.storage.DiskBlockObjectWriter.$anonfun$close$1(DiskBlockObjectWriter.scala:156)
                at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
                at org.apache.spark.storage.DiskBlockObjectWriter.close(DiskBlockObjectWriter.scala:158)
                at org.apache.spark.shuffle.sort.ShuffleExternalSorter.writeSortedFile(ShuffleExternalSorter.java:226)
                ... 13 more
```

Is there a way to specify some tmp directory? I couldn't find it here https://adam.readthedocs.io/en/latest/cli/actions/?highlight=duplicate . Much appreciate your help with the tool 😃

**Comment by heuermh** [comment]
If temporary disk is the problem, then this Spark configuration added before the `--` separator may help

`--conf spark.local.dir=/.../some/tmp/directory`

http://spark.apache.org/docs/latest/configuration.html

**Pull request closed without merging**
