### PR TITLE
default results should be null (fails on s3)

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
makes sense. I think we had this before

**Comment by asp8200** [comment]
Why are we setting `outdir` to `null`?  Does it mean that if the sure doesn't specify outdir to something else, then all the output-files will end up in `${projectRootDir}/null/`?

**Comment by asp8200** [comment]
> on aws, you need to specify the absolut path for the output. Having the default path there has caused failures for many people. So to be safe, across pipeline we went without default path but always have everyone set it manually

okay, so the pipeline will not run at all unless one sets `outdir` to something other than the default `null`?

**Review by asp8200 — APPROVED** [review]
A bit annoying we have to specify the `outdir` to `./results` in each test-yml, but I guess there was no other way 🤔

**Pull request merged**
