### PR TITLE
fix: spark issues

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by FriederikeHanssen — COMMENTED** [review]
Does this also fix @heuermh problems with the other modules?

**Comment by mahesh-panchal** [comment]
Out of curiosity what is the difference between `fixOwnership` and setting the user/group? Does that mean the user needs to be root (or whatever user is set by the container environment) in the docker container? If it needs another user, why doesn't this affect running in a singularity container, which automatically runs as user/group?

**Comment by maxulysse** [comment]
Basically it's just 2 way of doing the same thing.
The `fixOwnership` use chown to set up the owner of the files after the process is run.
The `runOptions` we have, change directly that in Docker, but `$HOME` becomes `/` instead of the default `/root`, which could make some tools fail (when they use `$HOME`).

**Comment by mahesh-panchal** [comment]
That would mean it's trying to use some files in `/root`, since the containers aren't usually started with a writable layer. Or do I misunderstand?
Otherwise I guess one could set the variables in the run option. I also see from the Nextflow code that there is a `userEmulation` flag that's not documented, which might set all that.

**Comment by maxulysse** [comment]
@nf-core/core @nf-core/sarek @heuermh @mahesh-panchal Can people test out and tell me if it works?
Thanks a lot, I'd really like to merge this one and prepare a minor release

**Review by mahesh-panchal — APPROVED** [review]

**Review by pontus — APPROVED** [review]
To reiterate (discussion in slack):

As of today, `userEmulation` includes the user runOptions as replaced, including mapping passwd and related files and home directory.

It will help in some cases, but will likely not change on e.g. macOS or if using some NSS-provider for user information (common for e.g. cluster setups and if using e.g. AD login).

It will also try to map the home directory which brings (in general) the risk of breaking stuff if something is picked up from the home directory instead of the container.

Both of these issues are not generally likely to appear and should be guarded against in the container (e.g. singularity by default maps the home directory, so it must be protected against anyway).

Overall, this is probably a slight improvement.

**Comment by mahesh-panchal** [comment]
I should add that `userEmulation` is an undocumented option. 
It's in the Nextflow code here though (https://github.com/nextflow-io/nextflow/blob/b41d126ddde2cf839fb70b57da99b9fd85e2dbb8/src/main/groovy/nextflow/util/DockerBuilder.groovy#L60,https://github.com/nextflow-io/nextflow/blob/b41d126ddde2cf839fb70b57da99b9fd85e2dbb8/src/main/groovy/nextflow/util/DockerBuilder.groovy#L107)

**Comment by maxulysse** [comment]
> I should add that `userEmulation` is an undocumented option.

I remember Paolo saying that the code is the documentation.
It was found, explained, we're now using it, it is hence documented :nerd_face:

**Comment by maxulysse** [comment]
Comment from @pditommaso on Slack:
> `userEmulation` is really an early days Docker hack, don’t use it

**Comment by pontus** [comment]
An alternative way of expressing it would be that spark requires special care. For the current sarek approach that's addressable, but for DSL2 I see no solution that doesn't involve maintaining a container for it.

**Pull request merged**
