### PR TITLE
Replacing local module BUILD_INTERVALS with nf-core mdule GAWK

### PR DESCRIPTION
**Pull request by asp8200**
Related to https://github.com/nf-core/modules/issues/5132#issuecomment-2004129253

If approved, then similar a change should be done in the raredisease-pipeline.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by maxulysse — DISMISSED** [review]

**Comment by FriederikeHanssen** [comment]
This PR scares me :D What are the output files now called?

**Review by maxulysse — APPROVED** [review]
<3

**Comment by FriederikeHanssen** [comment]
Before merging, can you test on the full size test? I am worried that the output name changing of the bed file could have effects we don't see on a smaller dataset. in the earlier days of sarek 3, we had issues in that direction

**Comment by asp8200** [comment]
> This PR scares me :D What are the output files now called?

I don't think the bed-file is or were published, but the output-file in the work-folder is called `genome.fasta.bed`. This is the `.command.sh` in the case of the simple test-profile with no supplied interval/bed :

```
awk \
    -v FS='     ' -v OFS='      ' '{ print $1, "0", $2 }' \
     \
    genome.fasta.fai \
    > genome.fasta.bed
```

The following is the `.command.sh` in the case of the simple test-profile with no supplied interval/bed - executed from the `dev`-branch:
```
awk -v FS='     ' -v OFS='      ' '{ print $1, "0", $2 }' genome.fasta.fai > genome.fasta.bed
```

**Comment by FriederikeHanssen** [comment]
no they are not published but they are used further in the pipeline.

**Comment by asp8200** [comment]
> Before merging, can you test on the full size test? I am worried that the output name changing of the bed file could have effects we don't see on a smaller dataset. in the earlier days of sarek 3, we had issues in that direction

Sure I can run the full-test. Better safe than sorry. Anything, in particular, I should pay attention to in my run of the full-test or is it fine if it completes without crashing?

**Comment by FriederikeHanssen** [comment]
I think if it runs through without crashing we are relatively save.

**Pull request merged**
