### PR TITLE
Add bam output for Preprocessing

### LINKED ISSUE #437: Allow saving of BAM files in 3.0

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
Closes #437 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
@maxulysse it works, it could be more efficient around the MD part. MD -> BAMTOCRAM -> QC (-> CRAMTOBAM). Unsure how much effort we should put in here.

**Comment by FriederikeHanssen** [comment]
Not sure why I didn't think about this before, but now just publishing out of markduplicates in case `--save_output_as_bam` is set. For spark still a conversion done, but it shouldn't matter if MD_SPARK outputs cram that we convert to bam for this parameter or if it produces BAM that we then need to convert to CRAM for the remaining pipeline

**Comment by FriederikeHanssen** [comment]
@nf-core-bot please fix prettier

**Comment by FriederikeHanssen** [comment]
@nf-core-bot please fix linting

**Comment by FriederikeHanssen** [comment]
🤨 ran prettier locally and CHANGELOG is fine/ nothing to commit. @maxulysse how do I make the bot help me?

**Review by maxulysse — APPROVED** [review]
<3
I love how you get the extension for the csv file

**Comment by maxulysse** [comment]
@nf-core-bot fix linting pretty please

**Pull request merged**
