### PR TITLE
Add GitHubActions

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Add GitHub Actions

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by MaxUlysse** [comment]
I think at the moment, that would be me ;-)

**Comment by drpatelh** [comment]
Good work @MaxUlysse ! So the only difference I can see between the  Travis CI tests and GitHub Actions are the two additional files `.github/workflows/ci.yml` and `.github/workflows/linting.yml` ? These look much simpler and I think its probably nicer to have these two tests running separately. Are these file auto-detected and triggered on GitHub Actions if they are placed in `.github/workflows/`?

**Comment by drpatelh** [comment]
Much quicker than Travis too!

**Comment by MaxUlysse** [comment]
Files are indeed auto-detected and triggered when place in `.github/workflows/`.

I could have put all tests into one file, but I figured that it would be better to run both tests separately as we don't need to download the docker image as well for the linting.

It's also much easier to make a matrix with ENV variables so you can more easily test multiple versions of different tools, or in sarek case, make multiple tests.

And I just scratched the surface with linting and CI, we could automate responses on PR and issues and so on...

**Comment by drpatelh** [comment]
Yeah, I saw the matrix testing from the number of checks that were carried out. Definitely a great start. Thanks for doing this! It looks good enough to me but maybe @ewels @sven1103 want to give it a once over too?

**Comment by MaxUlysse** [comment]
And then we can all look at https://github.com/nf-core/tools/pull/369 ;-)

**Comment by apeltzer** [comment]
Amazing job! Looks really good to me and I also like that you can split the lint and the actual tests in separate files...

**Pull request merged**
