### PR TITLE
add --aligner to choose between bwa-mem and bwa-mem2

### PR DESCRIPTION
**Pull request by MaxUlysse**
Struggling a bit to compute a conda env on my computer, with `bwa` and `bwa-mem2`, but also with either one of them.
So finally, opposed to what I said on Slack, I'm trying to have both of them at once, and see if it build on dockerhub.

# nf-core/sarek pull request

Many thanks for contributing to nf-core/sarek!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/sarek branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/sarek)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
Maybe I missed it, but if `bwa-mem2` is set for the `--aligner`, shouldn't then `params.bwa=false` be set by default, to avoid the indices mess? Or are you going to set them all in `igenomes` after all?

**Comment by MaxUlysse** [comment]
Default would be `bwa-mem` currently, so no issue with the current indices

**Comment by FriederikeHanssen** [comment]
OK, but if I set `--aligner-bwa-mem2`, then I have to set `bwa=false`, too, right? Maybe this can be already included, if this aligner is chosen?

**Comment by MaxUlysse** [comment]
That's a very good point.
I'll add that to the doc right away

**Review by FriederikeHanssen — APPROVED** [review]
The bwa changes look good. can't say much about the json schema. For me it looks good, but I haven't played around with it so far.

**Comment by MaxUlysse** [comment]
I know now that the conda env takes around 3 hours to compute, so trying again on my side to see if it all works well.
Hopefully can merge that today

**Review by FriederikeHanssen — APPROVED** [review]

**Pull request merged**
