### PR TITLE
Implemented MSISENSORPRO tumor-only analysis

### PR DESCRIPTION
**Pull request by bounlu**
Implements #1599 and #330

**MSIsensorpro** now also works with **tumor-only** samples if a baseline is provided by the user:
- Added `msisensor-pro pro` tumor-only analysis using the new module: https://github.com/nf-core/modules/pull/6350
- Providing `params.msisensorpro_baseline` will trigger tumor-only analysis independently from paired analysis
- Reference how to prepare `msisensorpro_baseline`: https://github.com/xjtu-omics/msisensor-pro/wiki/Best-Practices
- Paired analysis works as before if matched normal samples are provided in the samplesheet
- Also moved `msisensorpro_scan` to `params` supporting user-provided reference msi list for paired analysis

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by famosab** [comment]
I think you have to run `nf-core lint` locally and fix the installation of the msisensorpro module.

**Comment by bounlu** [comment]
I can't install `nf-core` as it conflicts with my conda environment.

**Comment by famosab** [comment]
Ok I found the issue: The module has to be finished first here https://github.com/nf-core/modules/pull/6350 and then be installed to sarek via `nf-core modules msisensorpro/msitumoronly`. Then the linting checks will be successful.

**Comment by bounlu** [comment]
Reopened PR

**Comment by bounlu** [comment]
Reopened PR

**Pull request closed without merging**
