### PR TITLE
Update test profile

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by FriederikeHanssen — COMMENTED** [review]
There is a doc section about what to expect from the tests, that would also need updating.

**Comment by maxulysse** [comment]
> There is a doc section about what to expect from the tests, that would also need updating.

We actually don't explain too much there, and I think now with the extensive work that @asp8200 did all the expected files are quite well explained in the `yml` files.
So I feel like we have enough there.

**Comment by FriederikeHanssen** [comment]
> > There is a doc section about what to expect from the tests, that would also need updating.
> 
> We actually don't explain too much there, and I think now with the extensive work that @asp8200 did all the expected files are quite well explained in the `yml` files. So I feel like we have enough there.

there is an example output though, that isnot up to date anymore. (otherwise we can also try this new rich click thing, if that works)

**Comment by maxulysse** [comment]
rich codex should be a separate PR, but I like the idea

**Review by FriederikeHanssen — APPROVED** [review]

**Pull request merged**
