### PR TITLE
Allow VEP to take a FASTA file for offline annotations

### LINKED ISSUE #1607: Allow specifying `--fasta` for VEP
### Description of feature

This is required to allow generation of HGVSc and HGVSp nomenclature when running offline (which is the default for sarek).

From the VEP docs:

> To generate HGVS identifiers when using [--cache](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_cache) or [--offline](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_offline) you must use a FASTA file and [--fasta](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fasta).

### PR DESCRIPTION
**Pull request by lbeltrame**
## Changes

Allows HGVS annotation when working offline. Fixes #1607.
I would like some feedback first on whether this is correct or should be gated behind some option.

## PR checklist

- [x] This comment contains a description of changes (with reason).

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
Great idea. Does https://nf-co.re/sarek/3.4.2/parameters/#vep_include_fasta not work?

**Comment by lbeltrame** [comment]
Oh! I think I missed it because I went looking into `conf` and didn't check the actual module! 
And looking for `--fasta` in code search didn't point me to the module for some reason...
Sorry for the noise!
Well, I can test, but this can be closed I think. 
For reference, do you think a PR for documentation would be better, instead?

**Comment by FriederikeHanssen** [comment]
> For reference, do you think a PR for documentation would be better, instead?

yes 💯 . If you didn't find it, we did a bad job at showing it. Maybe removing it form the hidden params would help?

**Comment by lbeltrame** [comment]
I think so, yes. I spent about 20-25 minutes wondering why I didn't have HGVS annotation despite the default options in Sarek allowing for it.

**Pull request closed without merging**
