### PR TITLE
Identified a WES ASCAT Error and updated documentation

### PR DESCRIPTION
**Pull request by alexanderchang1**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Usage Documentation in `docs/usage.md` is updated.

This is solely a documentation change in the usage.md file that allows using WES references provided by ASCAT, it's more user friendly than the currently recommended Battenberg method and also avoids a null-pointer error when running prepare.hts for ASCAT.

### CODE REVIEW

**Comment by maxulysse** [comment]
Can you update the CHANGELOG.md file?

**Comment by maxulysse** [comment]
@nf-core-bot fix linting pretty please :pray:

**Comment by alexanderchang1** [comment]
Added the changelog pull request in #1641

**Review by FriederikeHanssen — APPROVED** [review]
Thanks a lot!

**Pull request merged**
