### PR TITLE
nf-core modules update --all

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]

**Comment by FriederikeHanssen** [comment]
Hm, prematurely approved 😆  somethiing off with the target bed:

```
=================================== FAILURES ===================================
_________________________________ test session _________________________________
'Run default pipeline with target bed' exited with exit code '1' instead of '0'.
=========================== short test summary info ============================
FAILED tests/test_targeted.yml::Run default pipeline with target bed::exit code should be 0
=================== 1 failed, 21 passed in 292.13s (0:04:52) ===================
Error: Process completed with exit code 1.
```

**Comment by FriederikeHanssen** [comment]
Maybe the tabix module?

**Comment by maxulysse** [comment]
> Maybe the tabix module?

I'll investigate

**Comment by FriederikeHanssen** [comment]
The last test fails ```tests/test_targeted.yml .....................F``` are they checked by order in the yaml? Then it should be the ```- path: results/reports/samtools_stats/1234N/1234N.recal.cram.stats``` file 🤔 . But that module is not updated 😕

**Comment by maxulysse** [comment]
I reverted the tabix modules update, and it works.
I'm assuming there's some changes there that impact the rest of the downstream analysis.

**Comment by maxulysse** [comment]
I fixed some issues with the names of the files for the tabix modules.
I'll figure the tabix modules update in a separate PR.

**Pull request merged**
