### PR TITLE
setting snpeff directory name to lowercase in tower.yml

### LINKED ISSUE #1569: snpeff capitalization in tower.yml
The snpEff reports were not present in the 'reports' section of platform until I changed the capitalization of `snpEff` to all lower case to match the subdir name

https://github.com/nf-core/sarek/blob/b5b766d3b4ac89864f2fa07441cdc8844e70a79e/tower.yml#L56

https://github.com/nf-core/sarek/blob/b5b766d3b4ac89864f2fa07441cdc8844e70a79e/tower.yml#L54

### PR DESCRIPTION
**Pull request by cmatKhan**
closes #1569

### CODE REVIEW

**Comment by maxulysse** [comment]
Could you update CHANGELOG too?

**Comment by cmatKhan** [comment]
goodness...that was a mistake. I rebased my branch onto dev. That doesn't appear to be The Way. The changelog is updated, but I should probably just close this and re-open it so that the rest of the commits aren't present.

**Comment by FriederikeHanssen** [comment]
@cmatKhan I think we need to rebase or close and reopen this. somehow the spring changes are also picked up here

**Comment by cmatKhan** [comment]
Agreed

**Pull request closed without merging**
